"""change current to min temperature

Revision ID: 1b23905f9f46
Revises: 2b43a4434675
Create Date: 2024-06-23 18:16:54.743530

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b23905f9f46'
down_revision = '2b43a4434675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperatures', sa.Column('min', sa.Float(), nullable=False))
    op.drop_column('temperatures', 'current')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperatures', sa.Column('current', mysql.FLOAT(), nullable=False))
    op.drop_column('temperatures', 'min')
    # ### end Alembic commands ###
