"""add labeled field

Revision ID: 214ea5c3a523
Revises: cda43e89d3cb
Create Date: 2024-07-15 02:18:18.191738

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '214ea5c3a523'
down_revision = 'cda43e89d3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_images', sa.Column('labeled', sa.Boolean(), nullable=False))
    op.add_column('static_images', sa.Column('labeled', sa.Boolean(), nullable=False))
    op.add_column('uploaded_images', sa.Column('labeled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_images', 'labeled')
    op.drop_column('static_images', 'labeled')
    op.drop_column('dynamic_images', 'labeled')
    # ### end Alembic commands ###
