"""connect temperatures with dynamic images

Revision ID: 2b43a4434675
Revises: 2c82ba69f8b2
Create Date: 2024-06-14 14:05:41.581879

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2b43a4434675'
down_revision = '2c82ba69f8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('temperatures_ibfk_1', 'temperatures', type_='foreignkey')
    op.create_foreign_key(None, 'temperatures', 'dynamic_images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temperatures', type_='foreignkey')
    op.create_foreign_key('temperatures_ibfk_1', 'temperatures', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###
