"""updates

Revision ID: 2c82ba69f8b2
Revises: db909860ae1d
Create Date: 2024-06-04 23:55:58.055781

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c82ba69f8b2'
down_revision = 'db909860ae1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_images', sa.Column('predicted_disease_human_input', sa.Integer(), nullable=True))
    op.add_column('dynamic_images', sa.Column('is_sick_human_input', sa.Boolean(), nullable=True))
    op.alter_column('dynamic_images', 'predicted_disease',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('dynamic_images', 'is_sick',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_constraint('dynamic_images_ibfk_1', 'dynamic_images', type_='foreignkey')
    op.create_foreign_key(None, 'dynamic_images', 'diseases', ['predicted_disease_human_input'], ['id'])
    op.create_foreign_key(None, 'dynamic_images', 'diseases', ['predicted_disease'], ['id'])
    op.drop_column('dynamic_images', 'disease')
    op.drop_column('dynamic_images', 'is_sick_confirmed')
    op.drop_column('dynamic_images', 'confirmed_disease')
    op.add_column('static_images', sa.Column('predicted_disease_human_input', sa.Integer(), nullable=True))
    op.add_column('static_images', sa.Column('is_sick_human_input', sa.Boolean(), nullable=True))
    op.alter_column('static_images', 'predicted_disease',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('static_images', 'is_sick',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_constraint('static_images_ibfk_1', 'static_images', type_='foreignkey')
    op.create_foreign_key(None, 'static_images', 'diseases', ['predicted_disease_human_input'], ['id'])
    op.create_foreign_key(None, 'static_images', 'diseases', ['predicted_disease'], ['id'])
    op.drop_column('static_images', 'disease')
    op.drop_column('static_images', 'is_sick_confirmed')
    op.drop_column('static_images', 'confirmed_disease')
    op.add_column('uploaded_images', sa.Column('predicted_disease_human_input', sa.Integer(), nullable=True))
    op.add_column('uploaded_images', sa.Column('is_sick_human_input', sa.Boolean(), nullable=True))
    op.alter_column('uploaded_images', 'predicted_disease',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('uploaded_images', 'is_sick',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_constraint('uploaded_images_ibfk_1', 'uploaded_images', type_='foreignkey')
    op.create_foreign_key(None, 'uploaded_images', 'diseases', ['predicted_disease_human_input'], ['id'])
    op.create_foreign_key(None, 'uploaded_images', 'diseases', ['predicted_disease'], ['id'])
    op.drop_column('uploaded_images', 'disease')
    op.drop_column('uploaded_images', 'is_sick_confirmed')
    op.drop_column('uploaded_images', 'confirmed_disease')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_images', sa.Column('confirmed_disease', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('uploaded_images', sa.Column('is_sick_confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('uploaded_images', sa.Column('disease', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'uploaded_images', type_='foreignkey')
    op.drop_constraint(None, 'uploaded_images', type_='foreignkey')
    op.create_foreign_key('uploaded_images_ibfk_1', 'uploaded_images', 'diseases', ['disease'], ['id'])
    op.alter_column('uploaded_images', 'is_sick',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('uploaded_images', 'predicted_disease',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('uploaded_images', 'is_sick_human_input')
    op.drop_column('uploaded_images', 'predicted_disease_human_input')
    op.add_column('static_images', sa.Column('confirmed_disease', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('static_images', sa.Column('is_sick_confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('static_images', sa.Column('disease', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'static_images', type_='foreignkey')
    op.drop_constraint(None, 'static_images', type_='foreignkey')
    op.create_foreign_key('static_images_ibfk_1', 'static_images', 'diseases', ['disease'], ['id'])
    op.alter_column('static_images', 'is_sick',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('static_images', 'predicted_disease',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('static_images', 'is_sick_human_input')
    op.drop_column('static_images', 'predicted_disease_human_input')
    op.add_column('dynamic_images', sa.Column('confirmed_disease', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('dynamic_images', sa.Column('is_sick_confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('dynamic_images', sa.Column('disease', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dynamic_images', type_='foreignkey')
    op.drop_constraint(None, 'dynamic_images', type_='foreignkey')
    op.create_foreign_key('dynamic_images_ibfk_1', 'dynamic_images', 'diseases', ['disease'], ['id'])
    op.alter_column('dynamic_images', 'is_sick',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('dynamic_images', 'predicted_disease',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('dynamic_images', 'is_sick_human_input')
    op.drop_column('dynamic_images', 'predicted_disease_human_input')
    # ### end Alembic commands ###
