"""update defaults

Revision ID: 42b0c18164e8
Revises: daeb01491fc3
Create Date: 2024-03-29 00:45:32.981268

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '42b0c18164e8'
down_revision = 'daeb01491fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
