"""disease nullable

Revision ID: c675b4ce964b
Revises: 42b0c18164e8
Create Date: 2024-05-12 21:05:11.575128

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c675b4ce964b'
down_revision = '42b0c18164e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'disease',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'disease',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
